function [bag] = dqc_seastate_realtime_v1_2_spectrum_from_to(incoming_folder, work_folder, outgoing_folder, log_folder, sensor, station, date_from, date_to)

% Real-time quality control tests for spectrum (DWR, Radac, Radac Single)
% Looks for the timerange date_from to date_to (editable)

% spectrum: power density spectrum, *.spt / *.txt

% detailed_qc_flag (dqf) contains each test result for every evaluated parameter
% final_qc_flag (fqf) contains the worst (= max) flag from detailed_qc_flag

% flags for real-time data (CMEMS 2017)
% 0 = Not evaluated: Data have not been QC-tested, or the information on quality is not available.
% 1 = Pass: Data have passed critical real-time QC tests and are deemed adequate for use as preliminary data.
% 2 = Probably good data
% 3 = Probably bad data, potentially correctable
% 4 = Fail: Data are considered to have failed one or more critical real-time QC checks. If they are disseminated at all, it should be readily apparent that they are not of acceptable quality.
% 9 = Missing data: Data are missing; used as a placeholder.

% Generated by Mayumi Wilms (mayumi.wilms@bsh.de) on 2021/11/30 16:12:00

%% input information for script 
bag.s_incoming_folder = incoming_folder; % data folder
bag.s_work_folder = work_folder; % meta files folder
bag.s_outgoing_folder = outgoing_folder; % output files folder
bag.s_log_folder = log_folder; % log files folder
bag.s_sensor = upper(sensor); % sensor = 'DWR';
bag.s_station = station; % station = 'BUD';
bag.date_now = datetime('now','TimeZone','UTC');
bag.date_from = datetime(date_from,'TimeZone','UTC','InputFormat','yyyy-MM-dd HH:mm:ss.SSS');
bag.date_to = datetime(date_to,'TimeZone','UTC','InputFormat','yyyy-MM-dd HH:mm:ss.SSS');
switch upper(bag.s_sensor)
    case 'DWR'     
        bag.date_from_x = bag.date_from;
        bag.date_to_x = bag.date_to;
    
    case {'RADAC', 'RADAC_SINGLE'}
        bag.date_from_x = bag.date_from;
        bag.date_to_x = bag.date_to;
        
    case 'AWAC'
        
    otherwise
        warning('Unexpected sensor type.')     
end

%% check if folder exist
if ~isfolder(bag.s_incoming_folder)
    disp([datestr(bag.date_now) ' Incoming folder ' bag.s_incoming_folder ' does not exist.'])
    return
end

if ~isfolder(bag.s_work_folder)
    disp([datestr(bag.date_now) ' Work folder ' bag.s_work_folder ' does not exist.'])
    return
end

if ~isfolder(bag.s_outgoing_folder)
    disp([datestr(bag.date_now) ' Outgoing folder ' bag.s_outgoing_folder ' does not exist.'])
    return
end

if ~isfolder(fullfile(bag.s_incoming_folder,bag.s_station))
    disp([datestr(bag.date_now) ' Station folder ' fullfile(bag.s_incoming_folder,bag.s_station) ' does not exist.'])
    return
end

%% read metadatabase
s_MetaDatabase = fullfile(bag.s_work_folder,'Metadatenbank.xlsx');
bag.metadatabase = read_metadatabase(s_MetaDatabase,bag.s_sensor);      
   
if isempty(bag.metadatabase)
    disp([datestr(bag.date_now) ' Metadatabase ' s_MetaDatabase ' does not exist.'])
    return    
end

%% parser
switch upper(bag.s_sensor)
    case 'DWR' 
        % parser
        [bag] = parser_dwr_spectrum(bag);   

    case {'RADAC', 'RADAC_SINGLE'}
        % parser
        [bag] = parser_radac_spectrum(bag);      
        
    case 'AWAC'        
        
    otherwise
        warning('Unexpected sensor type.')
end

%% Date Test, Test 1
% checks if timestamps in datasets are logical
[bag] = DQC_Test01(bag);

%% Location Test, Test 2
% checks if lat and lon in gps.txt are correct; gps flag is handed over to
% the right timestamp of his, hiw, raw, spt; if a gps flag does not exist
% for a timestamp in his, hiw, raw, spt, the flag is 9 = missing value (for
% this timestamp)
[bag] = DQC_Test02(bag);

%% Completeness Test, Test 3
% checks for missing values in datasets, for raw and spt flags are computed
% when raw and spt are imported
[bag] = DQC_Test03(bag);
    
%%
for I2 = 1:1:height(bag.Table_SPT_dqf_03)
    if bag.Table_SPT_dqf_03.dqf_03_compl_spt(I2) == 1        
        switch upper(bag.s_sensor)
            case 'DWR'
                bag.Table_SPEC_temp = bag.Table_SPEC(bag.Table_SPT_dqf_03.Time(I2),:); % select one timestamp  
                bag.Table_SPT_temp = bag.Table_SPT(bag.Table_SPT_dqf_03.Time(I2),:); % select one timestamp       

            case {'RADAC', 'RADAC_SINGLE'}
                bag.Table_SPEC_temp = bag.Table_SPEC(bag.Table_SPT_dqf_03.Time(I2),:); % select one timestamp  

            case 'AWAC'

            otherwise
                warning('Unexpected sensor type.')     
        end 

        %% Range Test, Test 5
        % QARTOD, ST Time Series Range (Test 11) / Copernicus V1.1 (Test 7)
        % checks if values are within instrument and value ranges  
        [bag] = DQC_Test05(bag,I2);        

        %% Spectrum Test, Test 11
        % Test checks if spectral energy for the lower and higher areas 
        % (f <= 0.04 Hz or f => 0.6 Hz) contains more than 5 % of total
        % spectral energy (PDS_total), see SeaDataNet (2010, section 5.3);
        % Table_SPEC.SfSmax .* Table_SPT.Smax = S(f)
        [bag] = DQC_Test11(bag,I2);       
    
    else
        % tests could not be evaluated because dqf_03_compl_spt = 4
        bag.Table_SPT_qc0.dqf_Sf_05(bag.Table_SPT_dqf_03.dqf_03_compl_spt == 4) = 0; 
        bag.Table_SPT_qc0.dqf_Sf_11(bag.Table_SPT_dqf_03.dqf_03_compl_spt == 4) = 0; 
    end   
end; clear I2

%% final qc
% the order in detailed_qc_flag is essential because the position of
% the flags indicates the test number for which the flag is the result.
% therefore the timetable variables have to be sorted to make sure the
% order is right.
[bag] = DQC_FinalQC_from_to(bag);

%% format tables to specific format 
[bag] = DQC_Formatting(bag);

%% writetable
% writes the qc results (timestamp, detailed_qc_flag, final_qc_flag) in a
% text file.
[bag] = DQC_writetable_from_to(bag);

disp([datestr(bag.date_now) ' Data quality control for station ' bag.s_station ' (' bag.s_sensor ') was successful.'])

return