function T_TXT = read_txt_BO1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  T_TXT = read_txt_BO1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  T_TXT = read_txt_BO1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  T_TXT = read_txt_BO1("H:\MATLAB\DQC_Server\incoming\RADAC\BO1\BO1_2023-07.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Aug-2023 09:33:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = ["Time", "hsBo1", "airPres2", "airPres1", "airTemp1", "windVelM1", "windDirM1", "windGust1", "windTemp1", "airHum1", "lum1", "wavePeriod1", "waveDir1", "ts1", "hmax1", "hs1", "level2", "weatherCode1", "precip1", "vis1", "dewPoint1", "light1"];
opts.VariableNames = ["Time", "VAVH", "ATMP", "ATMS", "DRYT", "WSPD", "WDIR", "GSPD", "windTemp1", "RELH", "lum1", "wavePeriod1", "VPED", "VTPK", "VEMH", "VHZA", "SLEV_H1", "weatherCode1", "PRRT", "vis1", "DEWT", "light1"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "InputFormat", "yyyy-MM-dd'T'HH:mm:ss");
% opts = setvaropts(opts, ["hsBo1", "airPres2", "airPres1", "airTemp1", "windVelM1", "windDirM1", "windGust1", "windTemp1", "airHum1", "lum1", "wavePeriod1", "waveDir1", "ts1", "hmax1", "hs1", "level2", "weatherCode1", "precip1", "vis1", "dewPoint1", "light1"], "ThousandsSeparator", ",");
opts = setvaropts(opts, ["VAVH", "ATMP", "ATMS", "DRYT", "WSPD", "WDIR", "GSPD", "windTemp1", "RELH", "lum1", "wavePeriod1", "VPED", "VTPK", "VEMH", "VHZA", "SLEV_H1", "weatherCode1", "PRRT", "vis1", "DEWT", "light1"], "ThousandsSeparator", ",");

% Import the data
T_TXT = readtable(filename, opts);

T_TXT.Time.TimeZone = 'UTC';
T_TXT.Properties.VariableUnits =  {'', 'm', 'hPa', 'hPa', 'degrees_C', 'm s-1', 'degree', 'm s-1', 'degrees_C', '%', 'lux', 's', 'degree', 's', 'm', 'm', 'm', '', 'mm h-1', 'm', 'degrees_C', ''};
T_TXT.VEMH = T_TXT.VEMH * sqrt(2); % Hmax = 1.86*hs1 and hsbo1 = hs1 * sqrt(2) so Hmax is based on hsbo1 
% T_TXT.Time = T_TXT.Time - minutes(10); % bring timestamp to middle of measurement; deactivate because every parameter has a different measurement period

end