function T_CSV_381 = read_csv_0x381(filename, dataLines)
%IMPORTFILE Import data from a text file
%  T_CSV_381 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  T_CSV_381 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  T_CSV_381 = importfile("J:\70652{0x381}2023-01.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jul-2023 14:45:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Source", "Checksum", "MessageStamp", "TEMPK"];
opts.VariableTypes = ["categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Source", "EmptyFieldRule", "auto");

% Import the data
T_CSV_381 = readtable(filename, opts);
T_CSV_381.Time = datetime(T_CSV_381.MessageStamp./86400 + datenum(1970,1,1,0,0,0),'ConvertFrom','datenum','Format','dd-MMM-uuuu HH:mm:ss'); 
T_CSV_381.Time.TimeZone = 'UTC';
T_CSV_381.TEMP = T_CSV_381.TEMPK - 273.15;
T_CSV_381 = removevars(T_CSV_381, ["Source","Checksum","MessageStamp","TEMPK"]);

end